### ISSUE TITLE
Issue about map

### ISSUE THREAD

**Issue by Yang2Wang** [m-bone/AutoMapper#6]
Dear Automapper developer,
    Many thanks for your contributions to automatically generating templates of bond/react. 

    The command I ran is "**python3.7 AutoMapper.py . map cleanedBm-F6-pre.data cleanedBm-F6-post.data --save_name pre-molecule.data post-molecule.data --ba 68 182 68 182 --ebt N C O N C O H**"
    But I got an issue when I used **AutoMapper.py . map** command; 

"**Error: Missing Atom Search timed out. Atoms will be missing from the map. Please raise an issue on GitHub if the problem persists.**"

I don't know how to solve it, could you please give me some suggestions? And I attached the data file of pre-reaction and post-reaction. In the ZIP folder, there are four data files, named: "Bm-F6-pre.data" and "Bm-F6-post.data", which are generated from MS and converted to lammps format using PYSIMM. And other two files are generated from AutoMapper.py . clean command.
Best
Yang
[LAMMPS-data.zip](https://github.com/m-bone/AutoMapper/files/9497103/LAMMPS-data.zip)

**Comment by m-bone** [comment]
Hi Yang,

I've had a look at your files and you also form a new bond between atoms 66 and 183. You need to specify all the bonding atoms in the call so the --ba flag should be 68 182 66 183 68 182 66 183.

The masses in your cleaned files are also out of order e.g. type 1 is N in pre and O in post. These need to refer to the same types or AutoMapper wont work. Check you've used the clean command correctly and if it still doesn't work upload your coefficient file and I'll try it on my computer.

Thanks,

Matt

**Comment by Yang2Wang** [comment]
Thank you so much, you pointed out the key problem. But it is troublesome. I'll explain the procedure I did.

First, I create the un-reaction molecules in Materials Studio and then save it to .mol2 file, and next convert it to lammps data file with Dreiding force field using PYSIMM, I hope you know this package.

Second, I create the reacted molecules in Materials Studio and also save it to .mol2 file, and next convert it to lammps data file with Dreiding force field using PYSIMM, but the atom type order of these two data files is different. That is very annoying and I don't know how to solve that.

Now I'll upload the .mol2 files of pre- and post reaction and the reaction mechanism figure, if you have any ideas please let me know, I am really appreciated it. 
Also, I'll double-check the pysimm to see if there is a way to solve the atom type order issue.
![reaction](https://user-images.githubusercontent.com/112545290/188849460-845f3ce6-fd01-468d-8645-2b90efaf199e.jpg)

[mol2.zip](https://github.com/m-bone/AutoMapper/files/9504968/mol2.zip)

**Comment by Yang2Wang** [comment]
There is another question, --ba flag should only follow four atom IDs, so it can not type 68 182 66 183 68 182 66 183.

And I prepared the right pre- and post-reaction data files and you can have a look. Additionally, I also created the pre-reaction.template, post-reaction.template, and automap.data files in the zip folder.

Thanks.
[LAMMPS_datafiles.zip](https://github.com/m-bone/AutoMapper/files/9506090/LAMMPS_datafiles.zip)

**Comment by Yang2Wang** [comment]
Thank you so much, I updated the Automapper to v.1.10, but --ba flag can only have 4 atom IDs.  And I'll try moltemplate later.
![image](https://user-images.githubusercontent.com/112545290/189159830-3c90c724-6976-440c-993f-0cf64e132c7c.png)

**Comment by m-bone** [comment]
Ah apologies, I've not put it in as a new version, just added a new commit. If you git pull from the AutoMapper repo you should get it.

**Comment by Yang2Wang** [comment]
OK, that will be great, because my polymer is a bit complex, so it is difficult to build the model using moltemplate.

**Comment by m-bone** [comment]
Super, do you want to email hello@molydyn.com and we'll arrange a time there?

Best, Matt

**Comment by Yang2Wang** [comment]
Yes, thank you. 
But I am a little confused, you mean that I eamil to hello@molydyn.com first? And ask for arranging a time? for a meeting?

**Comment by m-bone** [comment]
Yes please, I'd rather not give away personal info on here 😊

**Comment by Yang2Wang** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Thank you so much, Matt. I think I figured this issue out now. You see the figure below, the crosslinking reaction is worked. I hope we can keep in touch if I have some new questions in the future. Thanks.
        Best Yang
    
        
            
        
    
    
         
        
            font{
            line-height: 1.6;
        }font{
            line-height: 1.6;
        }font{
            line-height: 1.6;
        }font{
            line-height: 1.6;
        }------------------------------------------------------------Yang WangPh. D. Student, (Visting Ph.D. Student in U of Groningen)Materials Science & Engineering University of Science & Technology BeijingBeijing, 100086, ChinaPhone: +86 17801234922Email: ***@***.***
        
    
     

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        9/9/2022 12:05
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [m-bone/AutoMapper] Issue about map (Issue #6)
        
      
    
  
  

Yes please, I'd rather not give away personal info on here 😊

**Comment by m-bone** [comment]
I can't see the images but I'm glad that it's worked! Please do get in touch if you've got any other issues. Best, Matt
